public enum EGameResolution
{
	NONE = 0,
	RAIDERS = 1,
	ARMY_RESCUE = 2,
	RECONSTRUCTION = 3,
	ROCKET = 4,
	VIPBUNKER = 5,
	CATS = 6,
	ABSENCE_UNKNOWN = 6,
	ABSENCE_RAIDERS = 7,
	ABSENCE_OTHERS = 8,
	ABSENCE_ARMY = 9,
	ABSENCE_CULT = 10,
	ABSENCE_CATS = 11
}
